### ISSUE TITLE
Improve handling of capitalization of field names.

### ISSUE THREAD

**Issue by kellertuer** [Humans-of-Julia/Bibliography.jl#14]
Consider the two following articles
````
@article{A,
    name = {A, B.},
    title = {A Title},
    jornal = {A Journal},
    year = {2020},
}

@article{B,
    NAME   = {A, B.},
    TITLE  = {A Title},
    JORNAL = {A Journal},
    YEAR   = {2020}
}
````
Both are valid bib(la)tex entries, and the second one is (up to renaming of the Key) even the paste of the first (parsed/improved by VS Code LaTeXWorkshop).

The first one loads perfectly fine, while the second one yields an error that all four fields `author`, `title`, `journal` and `year` are missing.

Could we maybe improve this and also accept capitalized field names?

**Comment by Azzaare** [comment]
@kellertuer this is solved now! (v0.2.7)

I plan to add an optional argument to keep the original case format of the different fields in the next version. Currently, everything will be lower-cased (including the type of entry).
