### ISSUE TITLE
Sorting of Bibliography

### ISSUE THREAD

**Issue by Azzaare** [Humans-of-Julia/Bibliography.jl#17]
This follow the issue in https://github.com/ali-ramadhan/DocumenterCitations.jl/issues/28

Ideally, several criteria for ordering should be available.

**Comment by LazyScholar** [comment]
Was tinkering on that end some time ago. And saw that you assigned that task to yourself.
I am only a beginner so not sure if it helps (so feel free to ignore it):
```julia
function sort_bibliography!(
    bibliography::DataStructures.OrderedDict{String,Entry};
    sorting_flag::Symbol = :key
    )
    if sorting_flag == :key
        sort!(bibliography);
    elseif sorting_flag == :authors_date
        sort!(bibliography,
              lt = isless_with_minor(a,b,:authors,:date),
              by = x -> bibliography[x]);
    else
        throw(ArgumentError("Unsupported sorting order!"));
    end
end

function isless_with_minor(a,b,field::Symbol,field_minor::Symbol)
    a1 = getfield(a,field);
    a2 = getfield(a,field_minor);
    b1 = getfield(b,field);
    b2 = getfield(b,field_minor);
    return (a1 == b1) ? (a2 < b2) : (a1 < b2);
end
```
The [isless()](https://docs.julialang.org/en/v1/base/base/#Base.isless) function for the specific data types of `Bibliography.jl` is not defined.

**Comment by Azzaare** [comment]
Nice! I would be more than glad to have help on this front (and others actually haha).

I have plans to put some important amount of time into Bibliography.jl and related projects this summer.
But anything that can be done with help is more time to do other things :)

I won't have time to help you much before a couple of days though.

**Comment by LazyScholar** [comment]
I am willing to help. But my tinkering brought up some questions which should be decided by the package maintainer.
1. sorting by separate function (like above)
1. sorting by insertion into `DataStructures.OrderedDict` -> using `DataStructures.SortedDict` -> different Dict type for whole Bib -> maintaining `OrderedDict` & `SortedDict` side by side and/or maybe further changes
1. supporting fixed sorting flags (like above)
1. or arbitrary combinations up to two or three (passing field symbols as a vector/tuple and prioritized sorting according to its entries) -> all data types have to support comparators
If it is okay to go with 1 and 3 i can try to implement some of the more important comparators `BibInternal.jl` (`:authors`,`:date`,`title`).

**Comment by Azzaare** [comment]
Thank you for the PR in BibInternal.jl. A new version has been tagged and should be released soon.

I think 1 and 3 are probably for the best, as progress (new flags) can be done incrementally.

**Comment by fingolfin** [comment]
This would be super cool, and also having it available in `DocumenterCitations.jl`. Currently, our bibliography looks like a random mess: https://oscar-system.github.io/Oscar.jl/dev/references/

**Comment by LazyScholar** [comment]
The changes for `DocumenterCitations.jl`#https://github.com/ali-ramadhan/DocumenterCitations.jl/issues/28 should be minimal if the #19 goes through:
```diff
--- a/src/DocumenterCitations.jl
+++ b/src/DocumenterCitations.jl
@@ -20,5 +20,6 @@ end
-function CitationBibliography(filename::AbstractString="")
+function CitationBibliography(filename::AbstractString="",sorting::Symbol=:none)
    filename == "" && return CitationBibliography(Dict())
    bf = import_bibtex(filename)
+   if sorting != :none; sort_bibliography!(bibliography,sorting); end
    return CitationBibliography(bf)
end
```

**Comment by Azzaare** [comment]
PR merged. I am about to register the new version in the General registry ;)

Thanks, @LazyScholar, for all the work!

**Comment by LazyScholar** [comment]
I will make a PR for `DocumenterCitations.jl` implementing as suggested above.

I have to thank too to be able to contribute a bit.

I think there is the need to open a new issue in the future as the sorting "implementation" by me is only rudimentary and might please the users only initially.

**Comment by fingolfin** [comment]
Any sorting would be better than what we have right now. Thank you all for working on this!!
