### ISSUE TITLE
Bibtex from String

### ISSUE THREAD

**Issue by davibarreira** [Humans-of-Julia/Bibliography.jl#20]
Is it possible to generate a BibTex from a string? For example, I have
"@misc{https://doi.org/10.5281/zenodo.4904586,\n  doi = {10.5281/ZENODO.4904586},\n  url = {https://zenodo.org/record/4904586},\n  author = {Zhang, Stephen and Widmann, David and {Davi Sales Barreira}},\n  title = {JuliaOptimalTransport/OptimalTransport.jl: v0.3.11},\n  publisher = {Zenodo},\n  year = {2021},\n  copyright = {Open Access}\n}\n", instead of a file.

**Comment by davibarreira** [comment]
Perhaps this should be done using BibParser directly.

**Comment by Azzaare** [comment]
Actually it should be available from both packages. Bibliography is the front-end so all important features (such as your suggestion) should be available.

**Comment by Azzaare** [comment]
In BibParser, parse_entry does the work and is not exported.

As I wrote these packages as a Julia beginner, a lot of things are not very clean. So I would rather use Bibliography as the API (to be able to refactor the internal packages as much as I want ^^)

Anyway, I, or anyone can add a function that wraps BibParser.parse_entry in Bibliography :)

**Comment by Azzaare** [comment]
@davibarreira `import_bibtex(input)` now parses input as a file if the file exists or as a string otherwise

Well, at least it will do once in the next version I should tag in a couple of hours.
