### ISSUE TITLE
Bug: key for `@misc` bib entries is lost

### ISSUE THREAD

**Issue by fingolfin** [Humans-of-Julia/Bibliography.jl#29]
Look at the `key` and `file` fields [in `test/test.bib.txt`](https://github.com/Humans-of-Julia/Bibliography.jl/blob/b23a0265a5e6ea4a5bad4e656d5699a458cc2fdd/test/test.bib.txt#L33-L39) to see what I mean.

**Comment by Azzaare** [comment]
This is coming from the parser. I will try to fix it asap.

**Comment by Azzaare** [comment]
Should be fixed with https://github.com/Humans-of-Julia/BibParser.jl/pull/21#issue-677739315

New BibParser.jl version has been submitted
