### ISSUE TITLE
Would that neat `join` trick also work in https://github.com/Humans-of-Julia/Bibliography.jl/blob/b23a0265a5e6ea4a5bad4e656d5699a458cc2fdd/src/staticweb.jl#L66-L133 ?

### ISSUE THREAD

**Issue by Azzaare** [Humans-of-Julia/Bibliography.jl#30]
From @LazyScholar in #28 (thanks by the way)

Would that neat `join` trick also work in https://github.com/Humans-of-Julia/Bibliography.jl/blob/b23a0265a5e6ea4a5bad4e656d5699a458cc2fdd/src/staticweb.jl#L66-L133 ?
I noticed in [your example](https://github.com/Humans-of-Julia/Bibliography.jl/issues/17#issuecomment-864058520) that it might be useful.
![ex](https://user-images.githubusercontent.com/75576197/123255084-b8585100-d4ef-11eb-972d-e15c172bdf71.png)

Edit:
And https://github.com/Humans-of-Julia/Bibliography.jl/blob/b23a0265a5e6ea4a5bad4e656d5699a458cc2fdd/src/staticweb.jl#L142-L154 could also return the arXiv link.

_Originally posted by @LazyScholar in https://github.com/Humans-of-Julia/Bibliography.jl/issues/28#issuecomment-867559824_

**Comment by LazyScholar** [comment]
The arXiv link can be removed from the issue. There is no arXiv field in the BibTex spec and it is recommended to use `archivePrefix` and `eprint` field to cite that correctly. So the current workaround to get a url via `DocumenterCitations.jl` should be to add the arXiv link to the BibTex `url` field.

For the empty fields with commas my only solution would be to throw a lot of `addstr != "" ? ", " : ""` onto it.
I think there might be a more elegant way but `join` might not work here.

Nevertheless this might be fixed or vanish after you add the custom cite formats you mentioned somewhere else.
