### ISSUE TITLE
Sort only by date

### ISSUE THREAD

**Issue by JinraeKim** [Humans-of-Julia/Bibliography.jl#36]
The [sorting rules](https://humans-of-julia.github.io/Bibliography.jl/stable/#Bibliography.sorting_rules) are too limited.
How about adding sorting rules such as sort only by date?

**Comment by JinraeKim** [comment]
Note that I'm trying to use this for CV.

**Comment by Azzaare** [comment]
This is a great idea. Sorry that I was super busy with other stuff for the last two weeks.

@LazyScholar do you want to have a look, or should I do it?

**Comment by Azzaare** [comment]
Thanks to @LazyScholar, this should be fixed now. You can use the `:y` keyword for sorting by year.

**Comment by JinraeKim** [comment]
Thanks!
