### ISSUE TITLE
.cff support

### ISSUE THREAD

**Issue by SebastianM-C** [Humans-of-Julia/Bibliography.jl#39]
Hi! Thanks for writing this package.
I was wondering if you would consider adding support for reading bibliography data from .cff files. I'm not sure if this feature request is in the scope of this package / org. I would like to add support for .cff files in PkgCite.jl (https://github.com/SebastianM-C/PkgCite.jl/issues/12), and a first step would be to have a package that can read the bibliography info.

**Comment by Azzaare** [comment]
Hi @SebastianM-C 

That is totally within the scope of this package. There are two steps for this to work:
- [ ] Parse .cff and convert the data to BibInternal.jl format (usually done in BibParser.jl)
- [ ] Export BibInternal format to .cff (in Bibliography.jl)

The second step is usually easier and can probably be done quickly.
As for the first step, we can either write the parser or interface an existing one.

I am planning to spend some time on Bibliography in the coming weeks (to add BibLaTeX and CL-JSON support), so it is a good timing.
